dist: xenial
#hey
install:
 - sudo apt-get install python
script:
 - python index.py
deploy:
 - provider: pages
 - skip_cleanup: true
 - github_token: "wdwdnnjdjde"
 - keep_history: true
 - on:
    branch:
     - master
      
